In [1]:
inputs = [1.2, 2.1, 5.9]
weights = [3.1, 2.3, 3.5]
bias = 3

output = inputs[0] * weights[0] + inputs[1] * weights[1] + inputs[2] * weights[2] + bias

In [2]:
print(output)

32.2


In [3]:
# what if we have multiple weights and bias
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, .26, -.5],
           [-.26, -.27, .17, .87]]
bias = [2, 3, .5]

layer_output = []
for neuron_weights, neuron_bias in zip(weights, bias):
    neuron_output = 0
    for n_input, weights in zip(inputs, neuron_weights):
        neuron_output += n_input*weights
    neuron_output += neuron_bias
    layer_output.append(neuron_output)
    
print(layer_output)

[4.8, 1.21, 2.385]


#### Understanding shape before moving further

l = [1,2,3,4]
        - shape = (4,)
        - type = 1D Array, Vector
        
l = [[1,2,3,4],
     [2,3,4,5]]
         - shape = (2,4)
         - type = 2D Array, Metrix
        
l = [  [ [1,2,3,4],
         [9,8,7,6] ]
       [ [2,3,4,5],
         [8,7,6,5] ]
       [ [3,4,5,6],
         [7,6,5,4] ]  ]
         - shape = (3,2,4)
         - type = 3D Array

## Dot Product

In [4]:
# Using Dot Product
import numpy as np
inputs = [1.2, 2.1, 5.9]
weights = [3.1, 2.3, 3.5]
bias = 3

output = np.dot(weights,inputs) + bias
output

32.2

In [5]:
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, .26, -.5],
           [-.26, -.27, .17, .87]]
bias = [2, 3, .5]

output = np.dot(weights,inputs) + bias
output

array([4.8  , 1.21 , 2.385])

### Batches
- The batchs are needed because if we provide one point at a time our model got disturbe and start behaving madly.
- Also if we provide all the values for training our model will over fit to all the values.
- To handel this batches are to be made so that our model work finly.


In [6]:
inputs = [[1, 2, 3, 2.5],
          [2, 5, 3, 2.5],
          [-1.5, 2.7, 3.3, -.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, .26, -.5],
           [-.26, -.27, .17, .87]]

bias = [2, 3, .5]

output = np.dot(weights,inputs) + bias
output

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

- The above portion gives error because when ever we multiply 2 metrices the row muptiply with columns
         Like first row with first columns and so on.
         row[3,4] and columns[3,4]
- But in our case we have 3 rows and 4 columns that's why it is throwing error.
- To handel this we first have to Transpose our weights.
         This will make 
                row[3,4] and columns[4,3]
                
- Row(Input) and Column(Weights)

In [7]:
inputs = [[1, 2, 3, 2.5],
          [2, 5, 3, 2.5],
          [-1.5, 2.7, 3.3, -.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, .26, -.5],
           [-.26, -.27, .17, .87]]

bias = [2, 3, .5]

output = np.dot(inputs, np.array(weights).T) + bias
output

array([[ 4.8  ,  1.21 ,  2.385],
       [ 7.4  , -1.02 ,  1.315],
       [ 1.41 ,  1.051,  0.026]])

Adding another layer of weight and biases

In [14]:
inputs = [[1, 2, 3, 2.5],
          [2, 5, -1, 2.5],
          [-1.5, 2.7, 3.3, -.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, .26, -.5],
           [-.26, -.27, .17, .87]]
bias = [2, 3, .5]

weights2 = [[0.5, 0.9, -0.5],
           [-0.5, 0.7, -.96],
           [-.26, .27, .57]]
bias2 = [1, -3, .9]

layer1_output = np.dot(inputs, np.array(weights).T) + bias

# now the output of layer one will the input for layer 2
layer2_output = np.dot(layer1_output, np.array(weights2).T) + bias2

print(layer2_output)

[[ 3.2965  -6.8426   1.33815]
 [ 3.5285  -9.7516  -1.73825]
 [ 2.6379  -2.99426  0.83199]]


We always have to keep in our mind that our data lie b/w -1 to 1 so that out data wont explode.
This is just an example thats why I have taken some hiher values.
But whenever we work with real data we have to first normalize our data so that we get good output

In [36]:
np.random.seed(0)
X = [[1, 2, 3, 2.5],                           #input feature set
     [2, 5, -1, 2.5],
     [-1.5, 2.7, 3.3, -.8]]

class layers:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)    # converting random values from range -1 to 1
        self.bias = np.zeros((1, n_neurons))
    def forword(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.bias


layer1 = layers(4,6)
layer2 = layers(6,3)

layer1.forword(X)
#print(layer1.output)

layer2.forword(layer1.output)
print(layer2.output)

[[ 0.14629144 -0.04806473 -0.00102545]
 [ 0.08093017 -0.17912034 -0.04057348]
 [ 0.09165886 -0.05176894 -0.09859882]]


## Activation Functions
- Sigmoid
- Step function
- ReLU (Most commonly used)(Fast){Rectified Linear Unit}

In [35]:
np.random.seed(0)
X = [[1, 2, 3, 2.5],                           #input feature set
     [2, 5, -1, 2.5],
     [-1.5, 2.7, 3.3, -.8]]

class layers:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)    # converting random values from range -1 to 1
        self.bias = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.bias

class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

layer1 = layers(4,5)
activation1 = Activation_ReLU()

layer1.forward(X)

print(layer1.output)
print()
print("{Basically Activation function here converts negative values to 0}")
print()
activation1.forward(layer1.output)
print(activation1.output)

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.06681425  0.78316807 -0.00732435  0.46266864  0.32090059]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]

{Basically Activation function here converts negative values to 0}

[[0.10758131 1.03983522 0.24462411 0.31821498 0.18851053]
 [0.         0.78316807 0.         0.46266864 0.32090059]
 [0.         0.55688422 0.07987797 0.         0.04553042]]
